name: 'CI: Starter Typescript Lambda'
on: [push]
jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'
      - run: |
          yarn install
          yarn build
          yarn package
      - name: CDK synth
        run: |
          yarn install
          yarn tsc
          yarn lint
          yarn test
          yarn synth
        working-directory: cdk
      - name: AWS Auth
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v2
        with:
          configPath: cdk/cdk.out/riff-raff.yaml
          projectName: playground::starter-typescript-lambda
          buildNumberOffset: 60
          contentDirectories: |
            cdk.out:
              - cdk/cdk.out/starter-typescript-lambda-CODE.template.json
              - cdk/cdk.out/starter-typescript-lambda-PROD.template.json
            starter-typescript-lambda:
              - cdk/starter-typescript-lambda.zip
